JBPM-7869 : NoClassDefFoundError warnings when starting Workbench RHPAM-1722 : NoClassDefFoundError warnings when starting Workbench (cherry picked from commit 388799ba11c18314571032bb3636f7ac7518c6ea)